export const uiRussian: Record<string, string> = {
  "Evidence Inbox": "Материалы проекта",
  "Passive evidence from connected sources and quick captures. Link it to an iteration in one step — or group a cluster.": "Добавляй фотографии, наблюдения и результаты. Объединяй материалы по этапам работы над роботом.",
  "Selected →": "С выбранными:",
  "Choose iteration…": "Выбрать этап…",
  "Iteration to link": "Связать с этапом",
  "Link to iteration": "Связать с этапом",
  "Subsystem…": "Узел робота…",
  "Subsystem": "Узел робота",
  "Set subsystem": "Указать узел",
  "New iteration title": "Название нового этапа",
  "Create iteration": "Создать этап",
  "Ignore": "В архив",
  "Restore to inbox": "Вернуть во входящие",
  "Mark sensitive": "Ограничить доступ",
  "Inbox is clear": "Новых материалов пока нет",
  "Nothing here yet.": "Здесь пока нет материалов.",
  "Start with a photo or connect GitHub. New commits, CAD revisions and chat captures will arrive here automatically.": "Добавь свою первую фотографию или наблюдение. Здесь будут появляться материалы твоего проекта.",
  "Capture": "Добавить материал",
  "Connect a source": "Подключить источник",
  "Open source ↗": "Открыть оригинал ↗",
  "Source inspector": "Подробности материала",
  "Possible iterations (deterministic suggestion)": "Материалы для объединения",
  "Suggested clusters": "Группы материалов",
  "Iteration title": "Название этапа",
  "Group into new iteration": "Объединить в этап",
  "Why?": "Обоснование",
  "Add the why": "Добавить объяснение",
  "Open iteration": "Открыть этап",
  "Details": "Подробности",
  "Source": "Источник",
  "Source evidence": "Исходный материал",
  "Student-authored": "Авторская запись",
  "System": "Система",
  "Suggestion": "Предложение",
  "AI-generated": "Создано ИИ",
  "Qualitative": "Качественная оценка",
  "present": "есть",
  "missing": "отсутствует",
  "open": "Открыт",
  "linked": "Связанные",
  "ignored": "Архив",
  "inbox": "Входящие",
  "sensitive": "Ограниченный доступ",
  "unknown author": "Автор не указан",
  "Settings": "Настройки",
  "Profile, language, notification preferences and your personal data controls.": "Профиль, язык и уведомления.",
  "Profile": "Профиль",
  "Display name": "Имя",
  "Age category (optional — never an exact birth date)": "Возрастная группа — необязательно",
  "Prefer not to say": "Не указывать",
  "Under 13": "Младше 13",
  "Notifications": "Уведомления",
  "Export ready": "Экспорт готов",
  "Competition policy updates": "Обновления правил соревнования",
  "Tests missing a decision (weekly at most)": "Испытания без решения — не чаще раза в неделю",
  "Save": "Сохранить",
  "Language": "Язык",
  "Your data": "Твои данные",
  "Export my contribution package (JSON)": "Скачать мои материалы (JSON)",
  "Session": "Вход в аккаунт",
  "Sign out securely": "Выйти из аккаунта",
  "Signing out clears queued offline captures and cached browser data on this device.": "При выходе будут очищены локальная очередь отправки и кеш на этом устройстве.",
  "Organization": "Организация",
  "Sign in": "Войти",
  "Create account": "Создать аккаунт",
  "Create your account": "Создать аккаунт",
  "Password": "Пароль",
  "Email": "Электронная почта",
  "At least 8 characters.": "Не менее 8 символов.",
  "Working…": "Подожди…",
  "New here?": "Нет аккаунта?",
  "Already have an account?": "Уже есть аккаунт?",
  "First name and initial is enough. We keep personal data minimal.": "Достаточно имени или псевдонима.",
  "Capture evidence": "Добавить материал",
  "Capture now, enrich later. The project and season are attached automatically, and offline work stays visible instead of disappearing.": "Сохрани фото, результат или наблюдение. Проект и сезон добавятся автоматически; записи без интернета останутся на устройстве.",
  "Saved on this device first": "Сначала сохраняется на устройстве",
  "Quick capture": "Новая запись",
  "What happened?": "Что произошло?",
  "Capture now. Enrich later. Known project context is attached automatically.": "Запиши главное сейчас. Подробности можно добавить позже.",
  "Close capture": "Закрыть запись",
  "Local outbox ·": "Очередь отправки ·",
  "capture": "запись",
  "could not sync.": "не удалось отправить.",
  "They remain on this device.": "Они сохранены на этом устройстве.",
  "Photo": "Фото",
  "Problem": "Проблема",
  "Test": "Испытание",
  "Decision": "Решение",
  "Reflection": "Наблюдение",
  "Title": "Название",
  "Description": "Описание",
  "Cancel": "Отмена",
  "Close": "Закрыть",
  "Back": "Назад",
  "Next": "Далее",
  "Search": "Поиск",
  "Apply": "Применить",
  "Reset": "Сбросить",
  "Loading…": "Загрузка…",
  "Retry": "Повторить",
  "Optional": "Необязательно",
  "Project": "Проект",
  "All subsystems": "Все узлы",
  "All time": "За всё время",
  "All relations": "Все связи",
  "Recent evidence": "Последние материалы",
  "Needs your context": "Нужны пояснения",
  "Active iteration": "Текущий этап",
  "Test bench": "Испытания",
  "Decision trail": "Решения",
  "Process health": "Состояние проекта",
  "Nothing is waiting for human rationale. Automatic sources are caught up.": "Материалов, требующих пояснений, пока нет.",
  "No active iteration. Open one when a concrete engineering change begins.": "Создай первый этап работы над роботом.",
  "GitHub, CAD, photo and capture events will appear here as source evidence.": "Здесь появятся твои фотографии, модели и наблюдения.",
  "No tests yet. Connect a change to an observed result before deciding.": "Испытаний пока нет. Запиши, что проверял и какой результат получил.",
  "No decision recorded yet. Decisions should follow evidence, not activity.": "Решений пока нет. Добавь вывод после первого испытания.",
  "Open all tests ↗": "Все испытания ↗",
  "Open decision trail ↗": "Все решения ↗",
  "Review policy ↗": "Правила проекта ↗",
  "Policy": "Правила",
  "Unlinked": "Без связей",
  "Authorship": "Авторство",
  "Preserved": "Сохранено",
  "Workspace": "Рабочая область",
  "Private": "Закрытая",
  "Clear": "В порядке",
  "Review": "Проверить",
  "Waiting": "Ожидание",
  "Captured": "Записано",
  "Recorded": "Записано",
  "Pending": "Ожидание",
  "No rationale gap": "Пояснения добавлены",
  "No test linked yet": "Испытание ещё не связано",
  "Decision still open": "Решение ещё не принято",
  "Human context": "Пояснения",
  "Latest validation": "Последняя проверка",
  "Latest choice": "Последнее решение",
  "Fit project": "Показать весь проект",
  "Reset workboard layout": "Сбросить расположение карточек",
  "Show canvas keyboard shortcuts": "Горячие клавиши",
  "Hide minimap": "Скрыть мини-карту",
  "Zoom to 100 percent": "Масштаб 100%",
  "Source facts are already captured. Add only the engineering reason the tools cannot know.": "Добавь объяснение к материалу.",
  "The part of the project currently moving from change to evidence to decision.": "Текущая работа: от изменения до проверки результата.",
  "Work arriving from code, CAD, capture and tests without rewriting it into a notebook.": "Материалы, которые ты добавляешь в проект.",
  "What was tested, what happened, and what decision the result should inform.": "Что проверили, что получилось и какие выводы сделали.",
  "The latest keep, iterate, reject and defer decisions with their evidence path.": "Последние решения и материалы, на которых они основаны.",
  "Policy, provenance and evidence gaps that could break the engineering record.": "Полнота записей и состояние проекта.",
  "A meaningful engineering change: problem → change → evidence → test → decision → next step.": "Этап работы: задача, изменение, материалы, испытание и вывод.",
  "A test connects a question or change to evidence and then to a decision. Record what was tested and what the result changed.": "Запиши, что проверяли, какой результат получили и как он повлиял на решение.",
  "No iterations yet": "Этапов пока нет",
  "No tests yet": "Испытаний пока нет",
  "No decisions match": "Решений пока нет",
  "No history in this range": "В этом периоде записей нет",
  "No linked evidence yet": "Связанных материалов пока нет",
  "No rejected approach has been documented yet": "Отклонённых вариантов пока нет",
  "No source evidence linked.": "Исходные материалы ещё не связаны.",
  "No test linked yet.": "Испытание ещё не связано.",
  "No decision linked yet.": "Решение ещё не связано.",
  "No decision linked": "Решение не связано",
  "No decision is linked to this yet — the “why” is not documented.": "Добавь решение и объясни его причину.",
  "No integrations connected.": "Подключений пока нет.",
  "No invites yet.": "Приглашений пока нет.",
  "No outputs created yet.": "Экспортов пока нет.",
  "No AI actions yet.": "Действий ИИ пока нет.",
  "No results": "Ничего не найдено",
  "No season": "Сезон не создан",
  "No subsystems in this season": "В этом сезоне узлы ещё не добавлены",
  "No sources yet. Start with a photo, or connect GitHub on the right.": "Добавь фотографию или подключи источник материалов.",
  "None": "Нет",
  "None yet.": "Пока нет.",
  "None documented": "Не записано",
  "Not documented.": "Не записано.",
  "Not documented yet.": "Пока не записано.",
  "Not written yet.": "Пока не записано.",
  "Rationale not documented.": "Обоснование не записано.",
  "Student conclusion not documented.": "Авторский вывод не записан.",
  "No iteration.": "Этап не указан.",
  "No supporting evidence is linked yet. This is an evidence gap, not a judgment about the decision.": "Свяжи решение с материалами или результатами испытаний.",
  "Source evidence, tests, decisions and iteration milestones will appear here as the project develops.": "Здесь появятся твои материалы, испытания и решения.",
  "Link source events to an iteration, record a test, and connect a decision. The trace appears from those real relationships — never from invented AI structure.": "Свяжи материалы с этапом, запиши испытание и решение. Граф построится по этим связям.",
  "Open one when you begin a change worth remembering. Inbox events can be grouped into an iteration in a single step.": "Создай этап для нового изменения. Материалы можно объединить в него из входящих.",
  "When an iteration closes as rejected or reverted, or a test fails, it appears here for future teams.": "Здесь сохраняются неудачные испытания и отклонённые решения, чтобы учитывать их в дальнейшей работе.",
  "Iterations": "Этапы",
  "Iteration": "Этап",
  "Iteration:": "Этап:",
  "Iteration context": "Подробности этапа",
  "Tests": "Испытания",
  "Test results": "Результаты испытаний",
  "Tests this week": "Испытания за неделю",
  "Decisions": "Решения",
  "Decisions this week": "Решения за неделю",
  "New decision": "Новое решение",
  "New test": "Новое испытание",
  "+ Decision": "+ Решение",
  "+ Test": "+ Испытание",
  "Open an iteration": "Создать этап",
  "Problem or goal": "Задача или цель",
  "Problem:": "Задача:",
  "What changed? (optional now)": "Что изменилось? — необязательно",
  "What will you change next?": "Что изменишь дальше?",
  "What will you change next? (optional)": "Что изменишь дальше? — необязательно",
  "Next step (optional)": "Следующий шаг — необязательно",
  "State": "Состояние",
  "Status": "Статус",
  "Status:": "Статус:",
  "Outcome": "Результат",
  "Outcome (if closing)": "Результат при завершении",
  "Update": "Обновить",
  "Question": "Вопрос",
  "Hypothesis": "Гипотеза",
  "Procedure": "Методика",
  "Procedure documented": "Методика записана",
  "Metric": "Показатель",
  "Value": "Значение",
  "Units": "Единицы",
  "Trials": "Попытки",
  "Successes": "Успешные попытки",
  "Pass criterion": "Критерий успеха",
  "Pass criterion stated": "Критерий успеха указан",
  "pass criterion:": "критерий успеха:",
  "Observations": "Наблюдения",
  "Pass": "Успешно",
  "Fail": "Неудача",
  "Inconclusive": "Недостаточно данных",
  "pass": "Успешно",
  "fail": "Неудача",
  "inconclusive": "Недостаточно данных",
  "keep": "Принять",
  "reject": "Отклонить",
  "iterate": "Доработать",
  "defer": "Отложить",
  "revert": "Вернуть прежний вариант",
  "unknown": "Не определено",
  "kept": "Принято",
  "rejected": "Отклонено",
  "deferred": "Отложено",
  "reverted": "Возвращён прежний вариант",
  "testing": "Испытания",
  "deciding": "Выбор решения",
  "closed": "Завершён",
  "draft": "Черновик",
  "Disposition": "Выбранное действие",
  "Alternatives considered": "Рассмотренные варианты",
  "Alternatives considered (optional)": "Другие варианты — необязательно",
  "Alternatives:": "Другие варианты:",
  "alternatives:": "другие варианты:",
  "Supporting test": "Подтверждающее испытание",
  "Supporting test (optional)": "Подтверждающее испытание — необязательно",
  "Supported by": "Основано на",
  "Link existing test": "Связать с испытанием",
  "Test to link": "Испытание для связи",
  "Link test": "Связать испытание",
  "Link": "Связать",
  "Link from Inbox": "Добавить из материалов",
  "Result": "Результат",
  "Measured result": "Измеренный результат",
  "Result / what changed next": "Результат и следующие изменения",
  "Decide from this test": "Принять решение по результату",
  "Test:": "Испытание:",
  "Decision:": "Решение:",
  "Decision ·": "Решение ·",
  "Date": "Дата",
  "Detail": "Подробности",
  "Add a note (student-authored, versioned)": "Добавить заметку",
  "Add note": "Добавить заметку",
  "Save note": "Сохранить заметку",
  "Save rationale": "Сохранить обоснование",
  "Save context": "Сохранить объяснение",
  "Save context →": "Сохранить объяснение →",
  "Saving creates a new annotation version; the original remains in history.": "Новая версия сохранится вместе с историей изменений.",
  "History": "История",
  "Revised": "Обновлено",
  "revised": "обновлено",
  "Student notes": "Авторские заметки",
  "Student rationale": "Авторское обоснование",
  "Coach note": "Заметка наставника",
  "Stored separately; never edits student content.": "Хранится отдельно от авторских записей.",
  "AI does not silently alter this rationale.": "ИИ не изменяет это обоснование.",
  "AI does not write or silently modify this field.": "Это поле заполняет автор.",
  "AI did not modify this text": "Текст не изменялся ИИ",
  "Comparison within iteration": "Сравнение внутри этапа",
  "Add a second quantitative test in the same iteration to see a before/after comparison.": "Добавь второе измерение в этот этап, чтобы сравнить результаты.",
  "Comparison.": "Сравнение.",
  "Rate": "Доля успешных попыток",
  "was": "было",
  "vs this": "по сравнению с текущим",
  "% relative change": "% относительного изменения",
  "Engineering Timeline": "История проекта",
  "Timeline": "Хронология",
  "Evidence Trace": "Связи проекта",
  "Evidence trace": "Связи проекта",
  "Trace graph": "Граф связей",
  "Follow the real path from source evidence through iteration and test to a decision. The canvas is read-only: relationships come from stored evidence, never invented structure.": "Проследи путь от материала через испытание к решению.",
  "Focus the trace": "Фильтры связей",
  "Keep the canvas readable. Narrow by subsystem, relationship or time before expanding the evidence field.": "Выбери узел робота, тип связи или период.",
  "Filter by subsystem or date. Scale changes time density and source-event aggregation — not card size.": "Выбери узел робота или период, чтобы найти нужные записи.",
  "Open in timeline": "Открыть хронологию",
  "Open in timeline →": "Открыть хронологию →",
  "Open in Trace": "Открыть граф",
  "Open trace": "Открыть граф",
  "Open source inspector": "Подробности материала",
  "Open full view": "Открыть полностью",
  "Inspect": "Подробнее",
  "Inspector": "Подробности",
  "Evidence inspector": "Подробности материала",
  "First-order relations": "Прямые связи",
  "No first-order relations in this filtered trace.": "Прямых связей по этим фильтрам нет.",
  "No explicit relations in this filtered trace.": "Связей по этим фильтрам нет.",
  "Select an evidence object to inspect its first-order relations, provenance and deep links.": "Выбери материал, чтобы увидеть его связи и подробности.",
  "Select a source event, iteration, test or decision to inspect its recorded time context and open the underlying evidence.": "Выбери запись для просмотра подробностей.",
  "Provider": "Источник",
  "Provider:": "Источник:",
  "Origin": "Происхождение",
  "Relationship": "Связь",
  "Relation type": "Тип связи",
  "From": "От",
  "To": "До",
  "Last 7 days": "Последние 7 дней",
  "Last 30 days": "Последние 30 дней",
  "Last 90 days": "Последние 90 дней",
  "All types": "Все типы",
  "All systems": "Все узлы",
  "Day": "День",
  "Month": "Месяц",
  "Scale": "Масштаб",
  "Date range": "Период",
  "Shape the time surface": "Настроить хронологию",
  "Fit history": "Показать всю историю",
  "Fit full history": "Показать всю историю",
  "Fit trace": "Показать весь граф",
  "Fit evidence trace": "Показать весь граф",
  "100% zoom": "Масштаб 100%",
  "Clear focus": "Снять выделение",
  "Return / clear focus": "Назад / снять выделение",
  "Pan": "Перемещение",
  "Move through time": "Перемещение по времени",
  "Navigate": "Навигация",
  "Help": "Помощь",
  "Canvas shortcuts": "Горячие клавиши",
  "Canvas keyboard shortcuts": "Горячие клавиши",
  "Timeline shortcuts": "Горячие клавиши хронологии",
  "Trace shortcuts": "Горячие клавиши графа",
  "Close inspector": "Закрыть подробности",
  "Close keyboard shortcuts": "Закрыть подсказки",
  "Close evidence inspector": "Закрыть подробности материала",
  "Close timeline inspector": "Закрыть подробности",
  "Resize inspector": "Изменить ширину панели",
  "objects": "объектов",
  "objects ·": "объектов ·",
  "relations": "связей",
  "Memory": "Память проекта",
  "Search project memory": "Поиск по проекту",
  "Search query": "Поисковый запрос",
  "Text search across iterations, tests, decisions, source events and student notes — scoped to your team.": "Найди этапы, испытания, решения и заметки своей команды.",
  "Retrieve why past engineering decisions happened from stored evidence. Search and deterministic retrieval work first; generative phrasing is only a policy-gated layer on top.": "Находи объяснения прежних решений по сохранённым материалам проекта.",
  "Question about project history": "Вопрос об истории проекта",
  "Ask project history": "Спросить о проекте",
  "Answer with project evidence": "Найти ответ в материалах",
  "Why did we choose this design?": "Почему мы выбрали эту конструкцию?",
  "Searches your team's evidence first": "Поиск по материалам твоей команды",
  "Evidence-first answers": "Ответы по материалам",
  "If there is not enough project evidence, Memory should say so instead of filling the gap.": "Если материалов недостаточно, система сообщит об этом.",
  "Source citations": "Ссылки на материалы",
  "Evidence citations stay attached so every useful answer has a path back to the original test, decision, iteration, or rationale.": "По ссылкам можно перейти к исходным испытаниям, решениям и заметкам.",
  "Example questions": "Вопросы к проекту",
  "Failure Library": "Опыт испытаний",
  "Rejected approaches and failed tests, with the student's own conclusion and the conditions under which a retry might make sense. Searchable across seasons.": "Неудачные испытания, отклонённые варианты и выводы команды за все сезоны.",
  "Rejected / reverted approaches ·": "Отклонённые варианты ·",
  "Failed tests ·": "Неудачные испытания ·",
  "Not related": "Не связано",
  "Related": "Связано",
  "Similar approach found in a previous season": "Похожий подход из прошлого сезона",
  "Engineering context changes — a past conclusion is a starting point, not a verdict.": "Условия меняются: используй прошлый вывод как отправную точку.",
  "Take or choose a photo": "Снять или выбрать фото",
  "Tap to replace photo": "Заменить фото",
  "JPEG, PNG or WebP · EXIF/GPS stripped before upload": "JPEG, PNG или WebP. Геоданные удаляются перед отправкой.",
  "What did you observe?": "Что ты заметил?",
  "What failed?": "Что не сработало?",
  "What were you testing?": "Что проверяли?",
  "What did you decide?": "Что решили?",
  "What did you learn?": "Что удалось узнать?",
  "Why did you choose this?": "Почему выбрали этот вариант?",
  "Why did you make this change?": "Почему внесли это изменение?",
  "We changed… because…": "Мы изменили… потому что…",
  "Quick observation (optional)": "Краткое наблюдение — необязательно",
  "Severity": "Влияние на работу",
  "Low — can continue": "Низкое — можно продолжать",
  "Medium — affects performance": "Среднее — влияет на результат",
  "High — blocks testing": "Высокое — мешает испытаниям",
  "Target / revision (optional)": "Объект или версия — необязательно",
  "Ratio result": "Успешные попытки из общего числа",
  "Open full capture": "Полная форма записи",
  "Open full capture ↗": "Полная форма ↗",
  "Open full capture for procedure, hypothesis and pass criteria": "Открыть полную форму с методикой, гипотезой и критерием успеха",
  "Open full capture for alternatives and next step": "Открыть полную форму с вариантами и следующим шагом",
  "Link project context": "Связать с проектом",
  "Capture type": "Тип записи",
  "Choose capture type": "Выбрать тип записи",
  "Sync now": "Отправить сейчас",
  "You are offline": "Нет подключения к интернету",
  "Capture still works. Anything you record is stored on this device and synced when the connection returns — nothing is lost.": "Записи сохраняются на устройстве и отправятся после восстановления связи.",
  "Student-authored capture is unavailable for this role": "Эта роль не может создавать авторские записи",
  "Capture unavailable for read-only role": "Для этой роли доступен только просмотр",
  "Coaches can view evidence but do not create student captures. Ask a student to record this observation.": "Наставник может просматривать материалы. Авторскую запись добавляет участник команды.",
  "Coaches view iterations; students open them.": "Наставники просматривают этапы, участники создают их.",
  "Current state": "Текущее состояние",
  "New subsystem": "Добавить узел",
  "New subsystem name": "Название узла",
  "Add": "Добавить",
  "Add subsystems from the engineering timeline or project setup.": "Добавь узлы в хронологии или настройках проекта.",
  "Subsystem not linked yet": "Узел ещё не указан",
  "Optional now": "Можно заполнить позже",
  "(optional now)": "(можно позже)",
  "(optional)": "(необязательно)",
  "(comma separated)": "(через запятую)",
  "(you)": "(ты)",
  "Team Members": "Участники команды",
  "Invite": "Пригласить",
  "Invite role": "Роль участника",
  "Max uses": "Количество использований",
  "Revoke": "Отозвать",
  "Set role": "Изменить роль",
  "Mark alumni": "Перевести в выпускники",
  "Reactivate": "Вернуть в команду",
  "student": "участник",
  "student lead": "лидер команды",
  "coach": "наставник",
  "active": "активен",
  "Invite code": "Код приглашения",
  "Invite not available": "Приглашение недоступно",
  "This invite is invalid, expired, revoked or already used. Ask your team lead for a new one.": "Приглашение недействительно или уже использовано. Попроси у лидера команды новое.",
  "Join": "Присоединиться",
  "Joining an existing team?": "Хочешь вступить в команду?",
  "Open the invite link your team lead shared, or paste the invite code:": "Открой ссылку от лидера команды или введи код:",
  "You were invited as": "Твоя роль по приглашению:",
  "You already belong to": "Ты уже состоишь в",
  "Create a private team": "Создать команду",
  "Team name": "Название команды",
  "Team number": "Номер команды",
  "Project / robot name": "Название проекта или робота",
  "Program": "Программа",
  "Season year": "Год сезона",
  "Timezone": "Часовой пояс",
  "Default language": "Язык по умолчанию",
  "Initial subsystems": "Узлы робота",
  "Keep this broad. You can change the taxonomy as the robot evolves.": "Список узлов можно менять по мере разработки робота.",
  "Create": "Создать",
  "Continue": "Продолжить",
  "Name the team and project. Everything starts private and can work before you connect a source.": "Укажи названия команды и проекта. Материалы доступны только участникам.",
  "Create the workspace first. Then capture manually or connect sources when the team is ready.": "Создай проект, затем добавляй свои материалы и подключай источники.",
  "Only what is necessary. Integrations can be connected later — the product works from your first photo.": "Начни с первого фото. Подключить другие инструменты можно позже.",
  "What are you building with?": "Какие инструменты вы используете?",
  "Set defaults once. Capture faster later.": "Настрой проект, чтобы быстрее добавлять записи.",
  "Workshop defaults": "Настройки проекта",
  "Setup progress": "Настройка проекта",
  "Setup ·": "Настройка ·",
  "Integrations": "Подключения",
  "Connected sources": "Подключённые источники",
  "Connect the tools your team already uses. Metadata only — we never ingest repository contents, and connector secrets are encrypted at rest.": "Подключи инструменты команды для сбора материалов. Секреты подключений хранятся зашифрованными.",
  "Team leads and coaches manage integrations.": "Подключениями управляют лидеры и наставники.",
  "Label": "Название",
  "Label (e.g. team/orion-robot)": "Название подключения",
  "Webhook URL": "Адрес вебхука",
  "Disconnect & revoke": "Отключить и отозвать доступ",
  "Telegram bot": "Бот Telegram",
  "Awaiting Onshape OAuth credentials on the server. The adapter, webhook route and data model are ready.": "Для подключения Onshape нужно настроить доступ OAuth на сервере.",
  "CSV test-data import": "Импорт результатов CSV",
  "CSV content": "Данные CSV",
  "Import CSV": "Импортировать CSV",
  "Import": "Импортировать",
  "Preview": "Просмотр",
  "Preview first; malformed numbers are reported, never coerced. Each row becomes a test with a provenance-linked source event.": "Проверь данные перед импортом. Каждая строка станет отдельной записью испытания.",
  "Title column": "Столбец названия",
  "Trials column": "Столбец попыток",
  "Successes column": "Столбец успехов",
  "Value column": "Столбец значения",
  "Units column": "Столбец единиц",
  "Date column": "Столбец даты",
  "title column": "столбец названия",
  "trials column": "столбец попыток",
  "successes column": "столбец успехов",
  "value column": "столбец значения",
  "units column": "столбец единиц",
  "date column": "столбец даты",
  "Outputs": "Экспорт",
  "Choose an output": "Выбрать формат",
  "Export history": "История экспорта",
  "Download": "Скачать",
  "Download output →": "Скачать →",
  "Build portfolio draft": "Создать черновик портфолио",
  "Build notebook view": "Создать инженерный журнал",
  "Build handoff": "Подготовить передачу проекта",
  "Export handoff": "Экспорт передачи проекта",
  "Engineering notebook view": "Инженерный журнал",
  "FTC portfolio": "Портфолио FTC",
  "One evidence base, multiple competition-safe views. Compose from linked evidence instead of maintaining duplicate documents.": "Создай документ из материалов проекта в нужном формате.",
  "Before export": "Перед экспортом",
  "Active export policy": "Правила экспорта",
  "Include disclosed AI-generated notes (policy-gated)": "Включить помеченные заметки ИИ, если разрешено правилами",
  "Output preview": "Просмотр документа",
  "Source details": "Подробности источника",
  "Model library": "Библиотека моделей",
  "Optimized size": "Размер файла",
  "Imported": "Добавлено",
  "3D model unavailable": "Модель недоступна",
  "Drag to inspect · Scroll to zoom": "Перетаскивай для вращения, прокручивай для масштаба",
  "Season": "Сезон",
  "Season handoff": "Передача проекта",
  "Create season": "Создать сезон",
  "Create a season to build a handoff.": "Создай сезон, чтобы подготовить передачу проекта.",
  "Start a new season": "Начать новый сезон",
  "Key decisions": "Основные решения",
  "Known failures": "Известные проблемы",
  "Important tests": "Основные испытания",
  "Unresolved questions": "Открытые вопросы",
  "Source history": "История материалов",
  "Mark handoff complete": "Завершить передачу",
  "What should next year's team know first about this subsystem?": "Что следующей команде нужно знать об этом узле?",
  "Start here next season · student-curated": "С чего начать следующий сезон",
  "Start here next season: major decisions, known failures, proven tests, unresolved questions and subsystem history — all derived from existing evidence. Nothing is invented; students curate the narrative.": "Сохрани для следующей команды решения, проблемы, испытания и открытые вопросы.",
  "Archives the current season, creates a new project and carries subsystem names forward. Past evidence stays linked and searchable.": "Текущий сезон сохранится в архиве. Новый проект получит список узлов, а старые материалы останутся доступны.",
  "Mark all read": "Прочитать все",
  "Nothing to report": "Новых уведомлений нет",
  "Low-pressure by design: no streaks, no daily guilt. Preferences are in Settings.": "Выбери нужные уведомления в настройках.",
  "You'll hear about exports that are ready, invitations, integration disconnects, policy updates and tests that still need a decision.": "Здесь будут уведомления об экспорте, приглашениях и изменениях проекта.",
  "My contribution": "Мой вклад",
  "Contribution Map": "Вклад участников",
  "Contribution evidence": "Материалы участника",
  "Export my evidence package": "Скачать мои материалы",
  "Engineering skill passport (private)": "Личный профиль опыта",
  "Private, evidence-backed view of your own work. Not a score, not a ranking, never shown to other students.": "Обзор твоих работ и связанных материалов. Видим только тебе.",
  "Every claim links to underlying evidence. There is no aggregate “engineering score” by design.": "Каждый вывод связан с материалами проекта.",
  "Authored by": "Автор",
  "By": "Автор:",
  "wrote": "написал(а)",
  "Latest": "Последние",
  "Today": "Сегодня",
  "Workbench": "Рабочая область",
  "TraceLab workbench": "Рабочая область TraceLab",
  "Primary navigation": "Основная навигация",
  "Primary workspace": "Разделы проекта",
  "Workspace utilities": "Инструменты проекта",
  "Spatial workspace tools": "Инструменты проекта",
  "Command palette": "Быстрый переход",
  "Search commands": "Поиск разделов",
  "Search / command": "Поиск и переход",
  "Search project, open evidence, capture…": "Найти раздел или добавить материал…",
  "No matching command.": "Ничего не найдено.",
  "Navigation": "Навигация",
  "Current lens": "Текущий вид",
  "Competition": "Соревнование",
  "Competition Mode": "Правила соревнования",
  "Competition profile": "Профиль соревнования",
  "Competition policy": "Правила соревнования",
  "Choose the rule context": "Выбрать правила",
  "Apply profile": "Применить профиль",
  "Only leads and coaches change the profile.": "Профиль меняют лидеры команды и наставники.",
  "Policy review pending.": "Правила требуют проверки.",
  "Policy details": "Подробности правил",
  "Policy Pack": "Набор правил",
  "Policy pack version": "Версия правил",
  "Policy Update Center": "Обновления правил",
  "Policy pinned ·": "Версия правил ·",
  "Last reviewed": "Последняя проверка",
  "Source URLs": "Ссылки на источники",
  "Effective action matrix": "Разрешённые действия",
  "Action matrix": "Разрешённые действия",
  "Action": "Действие",
  "Why this is restricted / allowed": "Объяснение ограничений",
  "Why this is restricted": "Причина ограничения",
  "Restricted AI actions blocked": "Ограниченные действия ИИ заблокированы",
  "AI provenance log": "История действий ИИ",
  "AI rewrite unavailable": "Переписывание ИИ недоступно",
  "Record a new policy version": "Добавить версию правил",
  "Version": "Версия",
  "Effective from": "Действует с",
  "Official source URLs (whitespace separated)": "Официальные ссылки — через пробел",
  "Changelog": "Описание изменений",
  "needs review": "нужна проверка",
  "reviewed": "проверено",
  "not reviewed": "не проверено",
  "strict": "строгий режим",
  "Protects student engineering work": "Защищает авторские материалы",
  "Process visibility, not surveillance. This view surfaces missing structure and intervention opportunities; it never ranks students by activity volume.": "Обзор полноты материалов проекта и вопросов, требующих внимания наставника.",
  "Project evidence health": "Состояние материалов",
  "Where the engineering record needs attention": "Что требует внимания",
  "Decision evidence": "Обоснования решений",
  "Missing rationale": "Без объяснения",
  "Tests → decisions": "Испытания → решения",
  "Testing recency": "Давность испытаний",
  "Interventions": "Нужна помощь",
  "Decision evidence gap": "Решение без материалов",
  "Test conclusion gap": "Испытание без вывода",
  "Review decision": "Посмотреть решение",
  "Review test": "Посмотреть испытание",
  "Open subsystem decisions": "Открытые решения по узлам",
  "Season, policy & integration health": "Сезон, правила и подключения",
  "No deterministic decision/test gaps detected. Continue reviewing context quality rather than chasing more activity.": "Связи между испытаниями и решениями заполнены.",
  "Organization name": "Название организации",
  "Organization access": "Доступ к организации",
  "Organization archive": "Архив организации",
  "Team archive": "Архив команды",
  "Team data": "Данные команды",
  "Archive & retention": "Архив и хранение",
  "Archive value comes from retaining engineering memory, not maximizing note volume.": "Архив хранит историю разработки для следующих сезонов.",
  "Save archive policy": "Сохранить правила хранения",
  "Unlinked inbox retention (days)": "Хранить несвязанные материалы — дней",
  "Keep indefinitely": "Хранить бессрочно",
  "Blank means keep indefinitely. Linked evidence, tests, decisions and student reasoning are never auto-deleted by this setting.": "Оставь пустым для бессрочного хранения. Связанные материалы эта настройка не удаляет.",
  "Delete team": "Удалить команду",
  "Irreversible. Type the exact team name to confirm. An audit event is recorded and storage cleanup is queued.": "Действие необратимо. Для подтверждения введи точное название команды.",
  "Audit trail": "История действий",
  "No organization-level audit events yet.": "Действий в организации пока нет.",
  "Team ownership": "Управление командой",
  "Seasons archived:": "Сезонов в архиве:",
  "Teams:": "Команды:",
  "Storage:": "Хранилище:",
  "members": "участников",
  "Plan": "План",
  "Research": "Исследование",
  "Research proof": "Данные исследования",
  "Research question": "Исследовательский вопрос",
  "Research question.": "Исследовательский вопрос.",
  "Experimental design": "План эксперимента",
  "Primary outcome measures": "Основные показатели",
  "Research integrity": "Достоверность исследования",
  "Competition experiment": "Эксперимент для конкурса",
  "Live, derived process evidence for the TraceLab study. These are team-level engineering signals — never a student leaderboard and never fabricated before/after results.": "Показатели, рассчитанные по реальным записям проекта.",
  "Measure the same team before and after adoption during real build → test → decision cycles.": "Сравни работу одной команды до и после внедрения на реальных циклах разработки и испытаний.",
  "The live cards above describe the current TraceLab dataset. They do not claim causal improvement. Before/after results must be collected separately and reported with sample size and dates.": "Карточки показывают текущее состояние проекта. Для выводов об улучшениях нужно отдельно собрать результаты до и после внедрения.",
  "Invalid email or password.": "Неверная почта или пароль.",
  "Something went wrong. Your data was not lost — please retry.": "Не удалось выполнить действие. Попробуй ещё раз.",
  "An account with this email already exists.": "Аккаунт с этой почтой уже существует.",
  "Author": "Автор",
  "Type": "Тип",
  "Open": "Открыть",
  "Why": "Обоснование",
  "Opened": "Начало",
  "Missing context": "Нужны пояснения",
  "Source events": "Материалы",
  "Source preserved": "Источник сохранён",
  "Open original source ↗": "Открыть оригинал ↗",
  "Student context": "Пояснение автора",
  "From the first part to the next discovery.": "От первой детали до нового открытия.",
  "Build": "Собирай",
  "Remember": "Сохраняй опыт",
  "Keep your robot models and revisions together.": "Храни модели робота и его деталей в одном проекте.",
  "Record real observations and results from the workshop.": "Записывай наблюдения и результаты реальных испытаний.",
  "Connect each decision to the materials that explain it.": "Связывай решения с материалами, которые помогают их понять.",
  "Your project, your evidence": "Твой робот. Твоя история.",
  "Start with your own photo, model or observation. Your workspace grows with your robot.": "Начни со своей фотографии, модели или наблюдения. Проект будет расти вместе с роботом.",
  "Start building": "Начать работу",
  "Exports use only your saved materials, tests and decisions. Create an output above to download the result.": "В экспорт входят только сохранённые материалы, испытания и решения. Выбери формат выше, чтобы скачать документ.",
  "Downloads are HTML documents. PDF page limits must be checked separately.": "Документы скачиваются в формате HTML. Ограничения по страницам PDF нужно проверять отдельно.",
  "Your evidence is everywhere.": "Все материалы — в одном проекте.",
  "Demo account:": "Тестовый вход:",
  "completed": "завершено",
  "in progress": "в работе",
  "No linked evidence": "Нет связанных материалов",
  "Autonomous": "Автономное управление",
  "Drivetrain": "Ходовая часть",
  "Intake": "Захват",
  "Lift": "Подъёмник",
  "Vision": "Машинное зрение",
  "photo": "Фотография",
  "problem": "Проблема",
  "reflection": "Наблюдение",
  "cad_revision": "Версия модели",
  "commit": "Изменение кода",
  "New roller geometry after the first pickup test": "Что показано на фотографии?",
  "Belt starts slipping after about 10 minutes of driving.": "Опиши замеченную проблему",
  "Intake pickup at 36 mm roller spacing": "Название испытания",
  "Prototype B · CAD rev 23 · commit a1b2c3d": "Версия робота или детали",
  "The ball stopped wedging after the second geometry change.": "Что произошло во время испытания?",
  "Keep 36 mm roller spacing": "Какое решение ты принял?",
  "36 mm scored 17/20 vs 11/20, and wedging disappeared across repeated runs.": "Какие результаты привели к этому решению?",
  "Intake reliability — roller spacing": "Название этапа работы",
  "Game piece occasionally jams between the rollers.": "Какую проблему нужно решить?",
  "e.g. Orion": "Название команды",
  "chain intake, 36 mm, overshoot…": "Найти материал, испытание или решение…",
  "2027 Season": "Название следующего сезона",
  "experimental detail": "Условия испытания",
  "success rate": "Доля успешных попыток",
  "s, cm, %": "с, см, %",
  "Decision state": "Результат решения",
  "The result you do not want to forget.": "Запиши результат, который важно сохранить.",
  "Student-authored · AI did not generate or rewrite this reflection.": "Это твои слова. ИИ не создаёт и не переписывает наблюдение.",
  "The source tells us what changed. Only your team can preserve why.": "Опиши причину изменения своими словами.",
  "Review evidence →": "Посмотреть материалы →",
  "Chronological evidence, student-authored rationale, tests and decisions. Deterministic under strict competition modes.": "Материалы по порядку, авторские пояснения, испытания и решения.",
  "Subsystem decisions, known failures, proven tests and unresolved questions for the next team.": "Решения по узлам, известные проблемы, испытания и открытые вопросы для следующей команды.",
  "A portable record of the evidence a student actually authored, tested, linked or contributed to — never a score.": "Документ с реальным вкладом участника в материалы и испытания проекта.",
  "Deterministic export allowed": "Экспорт сохранённых данных разрешён",
  "These are structural checks only. The composer never invents a stronger engineering story to satisfy a rubric.": "Проверяется наличие связей между записями. Отсутствующие результаты не придумываются.",
  "Every generated export record stores the policy decision/version so a later rule update does not rewrite history.": "Каждый экспорт сохраняет версию правил, действовавшую при его создании.",
  "Generated-content export is restricted:": "Экспорт сгенерированного текста ограничен:",
  "policy": "правила",
  "hash:": "Контрольная сумма:",
  "Linked decision": "Связанное решение",
  "Capture a test": "Записать испытание",
  "Understand what was tested, the result, and which engineering decision it informed. Qualitative tests remain first-class evidence — no number is forced.": "Записывай, что проверял, какой результат получил и какое решение принял. Результат можно описать словами.",
  "Structural check": "Проверка связей",
  "Result attached": "Результат сохранён",
  "Linked to an iteration": "Связано с этапом",
  "Decision linked": "Решение связано",
  "Deterministic checks only — nothing here writes content for you.": "Проверяется только структура. Текст остаётся твоим.",
  "Linked": "Связано",
  "Timeline filters": "Фильтры хронологии",
  "Trace filters": "Фильтры связей",
  "recorded objects": "записей",
  "No decision recorded. Evidence link missing.": "Решение пока не записано.",
  "Evidence link missing": "Связь с материалами не указана",
  "iteration ↗": "этап ↗",
  "Student-authored rationale": "Обоснование автора",
  "Problem → alternatives → tests → evidence → decision → next iteration. Missing links are shown neutrally as “evidence link missing”.": "Проблема, варианты, испытания и итоговое решение. Здесь видны сохранённые связи между ними.",
  "The decision exists, but its human rationale is missing. Add the why before treating this as complete engineering memory.": "Решение сохранено, но причина пока не указана. Добавь своё объяснение.",
  "(student-authored, versioned)": "(с сохранением истории изменений)",
  "Open evidence →": "Открыть материал →",
  "Rationale versions and linked source artifacts remain separate from the immutable decision record.": "История пояснений и исходные файлы сохраняются отдельно от решения.",
  "View Why? history": "История пояснений",
  "rationale versions preserved.": "версий пояснения сохранено.",
  "Trust": "Надёжность",
  "Student-authored text remains versioned.": "История авторского текста сохраняется.",
  "Evidence links are explicit relations.": "Связи с материалами указаны явно.",
  "What were you trying to improve or fix? Keep it in your own words — the source facts above are already preserved.": "Что ты хотел улучшить или исправить? Объясни своими словами.",
  "Student-authored field.": "Авторское пояснение.",
  "Coaches can review this evidence, but cannot write or rewrite a student's rationale.": "Наставник может просматривать материал, но не переписывать пояснение участника.",
  "version": "версия",
  "Done · open timeline →": "Готово — к хронологии →",
  "Source ↗": "Источник ↗",
  "action matrix": "правила действий",
  "Creates an immutable version; activating supersedes the previous active version. Historical exports stay pinned.": "Создаётся новая версия правил. Прошлые экспорты сохраняют прежнюю версию.",
  "What changed and where it was verified": "Что изменилось и где это проверено",
  "Sample text": "Текст для проверки",
  "of": "из",
  "Policy is executable server-side behavior. The interface shows what is protected, which actions are restricted, and which exact version governed an export or AI request.": "Правила применяются на сервере. Здесь видно, какие действия разрешены и какая версия правил действует.",
  "Trust guarantees": "Защита проекта",
  "Student-authored rationale preserved": "Пояснения автора защищены",
  "Source provenance preserved": "Происхождение материалов сохраняется",
  "Export checks enabled": "Проверки экспорта включены",
  "A newer competition manual may change AI/export rules. Current restrictions remain active until reviewed; evidence capture and deterministic exports continue to work.": "Правила конкурса могли измениться. До проверки действуют текущие ограничения; запись материалов остаётся доступной.",
  "modeled actions are currently restricted. A restriction is a policy decision, not a disabled-looking mystery control.": "действий ограничено текущими правилами.",
  "Authorship protection": "Защита авторства",
  "Student-Owned Mode": "Режим защиты авторства",
  "Preserves student-authored engineering content and disables generative transformations restricted by the active policy. This is executable policy, not a marketing toggle.": "Сохраняет авторский текст и запрещает изменения с помощью ИИ, не разрешённые правилами.",
  "Restricted action pattern": "Ограниченное действие",
  "This action could alter student-authored engineering evidence under the active competition policy. The system blocks it rather than silently changing the student's words.": "Это действие могло бы изменить авторский текст. Текущие правила его запрещают.",
  "The exact reason comes from the active action matrix above. Change the policy version only after reviewing the governing competition source.": "Причина ограничения указана в таблице выше. Меняй правила только после проверки регламента конкурса.",
  "Try the real gate": "Проверить ограничение",
  "Requests an AI rewrite of sample text through the existing server-side policy gate.": "Проверка запроса на переписывание текста через действующие правила.",
  "rewrite_student_text": "Переписать авторский текст",
  "grammar_improve_student_text": "Исправить грамматику",
  "generate_portfolio_text": "Создать текст портфолио",
  "generate_reflection": "Создать рефлексию",
  "search_evidence": "Поиск материалов",
  "team-level · not a ranking": "Показатели команды",
  "Ask the team which test, source artifact or observation actually supported this choice.": "Уточни у команды, какие испытания или наблюдения повлияли на выбор.",
  "The evidence exists; prompt students to record what this result changed or ruled out.": "Результат сохранён. Попроси участников описать, на что он повлиял.",
  "Coaches can leave coach notes on allowed surfaces but cannot rewrite student-authored rationale; the server enforces that boundary.": "Наставник может оставлять заметки, но не переписывать авторские пояснения участников.",
  "Iterations open > 3 weeks": "Этапы в работе дольше трёх недель",
  "Contribution context": "Участие команды",
  "active members connected evidence in the last 30 days. Treat this as a distribution signal, not a ranking or score.": "участников добавляли связи за последние 30 дней. Это не рейтинг.",
  "View evidence-based contribution summaries →": "Посмотреть вклад участников →",
  "Roles: student, student lead, coach. Coaches see everything but never author student content. Departing students become alumni — their contribution history stays intact.": "Наставники просматривают материалы, но не пишут за участников. История вклада сохраняется после выхода из команды.",
  "· joined": "· присоединился",
  "· expires": "· действует до",
  "Links expire after 7 days. Share the URL or the code; QR can be generated from the URL by any QR tool.": "Приглашение действует 7 дней. Передай ссылку или код участнику.",
  "Generative layer": "Помощь ИИ",
  "Only machine-assisted actions appear here. Deterministic retrieval does not need to masquerade as AI.": "Здесь отображаются только действия с помощью ИИ.",
  "Transparent by default": "Источники открыты для проверки",
  "Mark useful": "Полезно",
  "Reject": "Отклонить",
  "Multi-team continuity, archive controls and organization access. Team evidence remains private to each team.": "Управление командами, архивами и доступом. Материалы каждой команды остаются закрытыми.",
  "Multi-team continuity": "Преемственность команд",
  "Preserve seasons and operating context across teams without combining their private engineering records into a surveillance feed.": "Сохраняй сезоны и опыт команды, не объединяя закрытые материалы разных проектов.",
  "Continuity guardrails": "Правила хранения",
  "Team evidence stays scoped": "Материалы доступны своей команде",
  "Organization access does not turn private project evidence into one shared activity stream.": "Доступ к организации не объединяет закрытые материалы в общую ленту.",
  "Seasons remain recoverable": "Сезоны можно восстановить",
  "Retention is explicit": "Сроки хранения определены",
  "Only eligible unlinked inbox events follow retention settings; linked evidence and student reasoning are preserved.": "Автоочистка относится только к несвязанным входящим материалам. Связанные записи и пояснения сохраняются.",
  "· private team workspace": "· закрытый проект команды",
  "Organization roles manage continuity and administration; they do not grant silent authorship over student rationale.": "Роли организации дают административные права, но не право писать за участников.",
  "Delete team “": "Удалить команду «",
  "Evidence contributors": "Авторы материалов",
  "Context backlog": "Материалы без пояснений",
  "Unclosed test loop": "Испытания без решения",
  "Can passive provenance capture plus short student-authored rationale reduce documentation effort while improving retrieval of design rationale and evidence?": "Помогают ли автоматический сбор материалов и короткие пояснения сократить время документирования и быстрее находить причины решений?",
  "Independent variable.": "Независимая переменная.",
  "The TraceLab evidence layer. Keep GitHub, CAD, chat and normal workshop tools unchanged.": "Использование TraceLab. Остальные инструменты работы команды остаются прежними.",
  "Important.": "Важно.",
  "Context changes between seasons; treat past conclusions as a starting point.": "Условия меняются от сезона к сезону. Проверяй, применимы ли прошлые выводы сейчас.",
  "Type at least two characters. Tip: search a measurement like “36 mm” or a symptom like “jam”.": "Введи хотя бы два символа. Можно искать по размеру детали или описанию проблемы.",
  "Try fewer words, a different subsystem filter, or a synonym (e.g. “wedged” instead of “stuck”). Student notes are searched too.": "Попробуй сократить запрос, сменить узел или подобрать синоним. Поиск учитывает авторские заметки.",
  "You can export your own contribution evidence at any time, regardless of the organization's plan. Team evidence belongs to the team; your authorship on it is preserved even after you leave.": "Ты можешь скачать сведения о своём вкладе. Авторство сохраняется даже после выхода из команды.",
  "Account deletion and organization-level retention are handled by your team lead / organization admin (see": "Удалением аккаунта и хранением данных управляет руководитель команды или организации (см.",
  ") and documented in PRIVACY.md.": ") и правила хранения данных.",
  "Every statement above traces to a stored object. Missing pieces are reported as “not documented”, never inferred.": "Выводы опираются на сохранённые записи. Отсутствующие данные не додумываются.",
  "documentation": "Документация",
  "Open Capture": "Добавить материал",
  "Pin the rules to this season.": "Выбери правила сезона.",
  "The policy profile controls AI, authorship and export behavior. You can review it later in Competition Mode.": "Профиль определяет правила ИИ, авторства и экспорта. Его можно проверить в настройках конкурса.",
  "Policy is explicit, never guessed.": "Правила указываются явно.",
  "If a season rule is unknown or outdated, risky AI/export actions fail closed until the policy is reviewed.": "Если правила неизвестны или устарели, ограниченные действия ИИ и экспорта недоступны до проверки.",
  "These values help timestamps, labels and subsystem capture. They remain editable in Settings.": "Эти настройки используются для дат и узлов робота. Позже их можно изменить.",
  "English": "English",
  "Private by default.": "Проект закрыт по умолчанию.",
  "Student-Owned Mode is on by default.": "Защита авторства включена по умолчанию.",
  "Generative assistance is available only where the selected competition policy explicitly permits it.": "Помощь генеративного ИИ доступна только там, где её разрешают правила конкурса.",
  "· Set up": "· Настройка",
  "team": "команда",
  "Open workspace": "Открыть проект",
  "Trust & safety": "Безопасность",
  "Pricing": "Тарифы",
  "Core capture, evidence, exports and competition safety are free. Paid plans add organization scale.": "Основные функции записи, хранения и экспорта бесплатны. Платные тарифы предназначены для организаций.",
  "Never paywalled:": "Всегда доступны:",
  "privacy controls, personal and team data export, competition-policy gating, Student-Owned Mode.": "настройки приватности, экспорт данных и защита авторства.",
  "Billing provider is not configured in this deployment; plan changes use the development adapter.": "Платёжная система не подключена. Изменение тарифа работает в тестовом режиме.",
  "Trust center": "Центр безопасности",
  "How": "Как",
  "protects student engineering work": "защищает инженерную работу",
  "Plain statements about what the product does — and does not — do. Policy snapshot date:": "Возможности и ограничения продукта. Дата проверки правил:",
  "Timeline controls": "Управление хронологией",
  "Timeline density": "Плотность хронологии",
  "Select timeline event": "Выбрать запись",
  "Engineering inspector": "Подробности записи",
  "Event type": "Тип записи",
  "No iteration membership is stored for this timeline object.": "Запись пока не связана с этапом.",
  "Chronological explorer": "Хронология",
  "Recorded engineering history ·": "История проекта ·",
  "Recorded engineering history in a simple ordered representation. Use this when spatial positioning is not useful or when reviewing with assistive technology.": "Материалы проекта в хронологическом порядке.",
  "Mobile Engineering Timeline": "Хронология проекта",
  "Inspect timeline event": "Подробности записи",
  "Mobile timeline inspector": "Подробности записи",
  "Close mobile timeline inspector": "Закрыть подробности",
  "Spatial Engineering Timeline": "Хронология проекта",
  "Trace Replay ·": "Просмотр истории ·",
  "Close Timeline shortcuts": "Закрыть подсказки",
  "Select previous / next evidence": "Предыдущая / следующая запись",
  "Focus selected evidence": "Показать выбранную запись",
  "Play / pause Trace Replay": "Запустить / остановить просмотр",
  "Evidence Trace keyboard shortcuts": "Горячие клавиши графа",
  "Close Evidence Trace keyboard shortcuts": "Закрыть подсказки",
  "Evidence Trace canvas controls": "Управление графом",
  "Fit trace · F / 0": "Показать весь граф · F / 0",
  "FIT": "Вместить",
  "Zoom evidence trace to 100 percent": "Масштаб 100%",
  "Show Evidence Trace keyboard shortcuts": "Показать горячие клавиши",
  "Keyboard help · ?": "Горячие клавиши · ?",
  "Accessible trace": "Список связей",
  "Relation explorer": "Связи проекта",
  "Focused evidence trace": "Выбранные связи",
  "Primary": "Главное",
  "How it works": "Как это работает",
  "Showcase": "Обзор",
  "Docs": "Помощь",
  "Keyboard-first navigation · evidence stays primary": "Быстрый переход к разделу",
  "Interactive 3D model of Prototype 999": "Интерактивная модель прототипа 999",
  "Calibrating model": "Подготовка модели",
  "Explain why, from linked evidence": "Пояснение на основе связанных материалов",
  "Canvas controls": "Управление рабочим полем",
  "Fit project · F / 0": "Показать весь проект · F / 0",
  "Toggle minimap": "Показать или скрыть миникарту",
  "Spatial workbench": "Рабочий стол",
  "Swipe →": "Листай →",
  "Mobile workbench boards": "Карточки проекта",
  "Inspect board": "Открыть подробности",
  "Mobile workbench inspector": "Подробности проекта",
  "Mobile inspector": "Подробности",
  "Close mobile inspector": "Закрыть подробности",
  "Open the canonical view for the complete evidence record and provenance.": "Открой раздел, чтобы увидеть все записи.",
  "Focus selected board": "Показать выбранную карточку",
  "Back one spatial layer": "Назад",
  "Spatial Evidence Workbench": "Рабочий стол проекта",
  "Workbench context": "Контекст проекта",
  "· Spatial workbench": "· Рабочий стол",
  "need why": "без пояснения",
  "More evidence needing context": "Материалы без пояснений",
  "Current engineering evidence loop": "Этапы работы",
  "Source → rationale → test → decision → next iteration": "Материал → пояснение → испытание → решение → следующий этап",
  "Your robot, one step at a time.": "Сборка, испытания и решения — всё о твоём роботе.",
  "Canvas view": "На рабочем поле",
  "Overview": "К обзору",
  "Preserve a physical build or revision.": "Сохрани фотографию сборки или детали.",
  "Record something the team noticed.": "Запиши замеченную проблему.",
  "Capture a result before details disappear.": "Сохрани результат испытания.",
  "Keep what you chose and why.": "Зафиксируй выбор и его причину.",
  "Student-authored learning and next step.": "Запиши вывод и следующий шаг.",
  "What changed in this photo?": "Что изменилось на фотографии?",
  "Take the photo first. Add only the context someone else would not know from looking at it.": "Сначала добавь фотографию. Затем поясни то, что не видно на снимке.",
  "What did you notice?": "Что ты заметил?",
  "Describe the symptom, not a polished explanation. You can link it to an iteration later.": "Опиши проблему своими словами. Связать её с этапом можно позже.",
  "A title and result are enough to save now. Experimental detail can be added when it matters.": "Для начала достаточно названия и результата. Условия испытания можно добавить позже.",
  "What did you decide — and why?": "Какое решение ты принял и почему?",
  "The reasoning stays student-authored. Link supporting evidence if it already exists.": "Объясни причину своими словами. Если есть подтверждающие материалы — свяжи их.",
  "Capture your own words. TraceLab does not generate or rewrite reflection content.": "Запиши своими словами. TraceLab не создаёт и не переписывает твои выводы.",
  "Saved locally": "Сохранено на устройстве",
  "Uploads resume automatically when connected": "Отправка продолжится при подключении к сети",
  "All captures synced": "Все записи синхронизированы",
  "Device is online": "Есть подключение к сети",
  "Saving on this device…": "Сохраняем на устройстве…",
  "Save capture": "Сохранить запись",
  "Choose or take a photo first.": "Сначала выбери или сделай фотографию.",
  "A decision needs your reason (why).": "Укажи причину решения.",
  "Saved to project.": "Сохранено в проекте.",
  "Capture saved.": "Запись сохранена.",
  "Chronological evidence": "Материалы по порядку",
  "Record a decision with its rationale from Capture.": "Запиши решение и его причину через «Добавить материал».",
  "Similar past work will be surfaced as a suggestion — “we already tried this”.": "Связанные прошлые работы появятся как подсказки.",
  "Search memory": "Найти в истории",
  "Read engineering work through time: source evidence, iteration boundaries, tests and decisions stay distinct while real iteration membership becomes visible.": "История материалов, этапов, испытаний и решений проекта.",
  "Show evidence trace minimap": "Показать миникарту",
  "Output selector": "Форматы экспорта",
  "Validation & trust checks": "Проверка перед экспортом",
  "REQUIRE REVIEW": "Требуется проверка",
  "REQUIRE_REVIEW": "Требуется проверка",
  "READY": "Готово",
  "Evidence-first composition.": "Документ на основе сохранённых материалов.",
  "ftc portfolio": "Портфолио FTC",
  "Kicker insert prototype with the supplied glossy yellow material.": "Прототип детали с исходным жёлтым материалом.",
  "Optimized browser edition of the attached 3209 robotic assembly.": "Сборка 3209, подготовленная для просмотра в браузере.",
  "FTC 2026–27 BIOBUZZ (policy pending review)": "FTC 2026–27 BIOBUZZ (правила требуют проверки)",
  "Connect": "Подключить",
  "Connecting…": "Подключение…",
  "Authorize with": "Подключить через",
  "Create a webhook (or GitHub App) pointing at the URL shown after connecting. Push events → one source event per commit: SHA, author, branch, message, changed-file counts.": "После подключения настрой вебхук GitHub на указанный адрес. В проект будут поступать сведения о коммитах: автор, ветка, сообщение и число изменённых файлов.",
  "Server is missing ONSHAPE_CLIENT_ID / ONSHAPE_CLIENT_SECRET. You can pre-register the document; the connection stays pending until OAuth completes.": "Подключение Onshape ещё не настроено на сервере. Можно сохранить документ; синхронизация начнётся после настройки OAuth.",
  "Create a bot with @BotFather, paste a secret token you choose here, then call setWebhook with the URL and the same secret_token. Messages with #tags and photos become evidence.": "Создай бота через @BotFather и настрой вебхук с выбранным секретным токеном. Сообщения с тегами и фотографии будут добавляться в проект.",
  "Route channel messages to the webhook URL via a bot relay that sets the X-Trace-Webhook-Secret header (secret shown once after connecting).": "Настрой бота для отправки сообщений на адрес вебхука с заголовком X-Trace-Webhook-Secret. Секрет показывается один раз после подключения.",
  "Mechanical": "Механика",
  "Experimentation": "Испытания",
  "Programming": "Программирование",
  "Mechanical design": "Проектирование механизмов",
  "Iteration & decision-making": "Разработка и решения",
  "Documentation": "Документирование",
  "linked to evidence": "связано с материалами",
  "No evidence recorded yet.": "Материалов пока нет.",
  "Time to retrieve a 2–3 month old design decision": "Время поиска решения, принятого 2–3 месяца назад",
  "Time to locate the test supporting that decision": "Время поиска испытания, подтверждающего решение",
  "Decision evidence-link rate": "Доля решений со связанными материалами",
  "Manual documentation time per meaningful engineering change": "Время документирования одного значимого изменения",
  "Distributed contributor rate": "Доля участников, добавляющих материалы",
  "Portfolio/evidence preparation time": "Время подготовки портфолио и материалов",
  "The active rule pack controls AI, authorship-sensitive actions and exports. Research snapshot: 2026-09-03. No official certification is claimed.": "Действующие правила определяют доступность ИИ, редактирования и экспорта. Снимок правил: 03.09.2026. Приложение не имеет официальной сертификации конкурсов.",
  "· Competition Mode": "· Правила конкурса",
  "Current season rules require review before AI-assisted competition actions are enabled.": "Перед включением ИИ нужно проверить правила текущего сезона.",
  "summarize_for_export": "Сократить текст для экспорта",
  "organize_notebook_content": "Упорядочить содержимое дневника",
  "generate_notebook_outline": "Создать план дневника",
  "generate_code": "Сгенерировать код",
  "transcribe_voice_exact": "Точная расшифровка речи",
  "transcribe_and_cleanup_voice": "Расшифровка и обработка речи",
  "suggest_structural_gap": "Найти пропущенные связи",
  "retrieve_evidence": "Найти материалы",
  "generate_ai_memory_answer": "Ответ ИИ по истории проекта",
  "export_generated_content": "Экспорт текста ИИ",
  "export_deterministic_notebook": "Экспорт сохранённого дневника",
  "coach_edit_student_content": "Изменение авторского текста наставником",
  "ALLOW": "Разрешено",
  "ALLOW WITH DISCLOSURE": "Разрешено с указанием ИИ",
  "BLOCK": "Запрещено",
  "Deterministic evidence action; no generative transformation.": "Работа с сохранёнными данными без генерации текста.",
  "Blocked by the pending policy version.": "Запрещено до проверки правил.",
  "Coaches and administrators cannot edit student-authored engineering content.": "Наставники и администраторы не могут редактировать авторские инженерные пояснения.",
  "ENABLED": "Включено",
  "DISABLED": "Выключено",
  "Disable": "Выключить ",
  "Enable": "Включить ",
  "Request transformation": "Проверить действие",
  "Not reviewed": "Не проверено",
  "NEEDS_REVIEW": "Нужна проверка",
  "Generic engineering (no competition)": "Инженерный проект вне конкурса",
  "No competition restrictions. Generative assistance is allowed with disclosure; student reflection is never generated.": "Конкурсные ограничения не применяются. Помощь ИИ требует раскрытия; авторская рефлексия не генерируется.",
  "FTC 2025–26 DECODE (archived)": "FTC 2025–26 DECODE (архив)",
  "Historical policy version for the 2025–26 season. Portfolio: cover + up to 15 content pages, file-size limits, minimize PII, judges do not follow external links; AI composition was allowed when appropriately credited.": "Архивная версия правил сезона 2025–26: обложка и до 15 страниц портфолио, ограничения размера файла и персональных данных. Внешние ссылки не проверяются жюри; использование ИИ требовало указания.",
  "The 2026–27 challenge launches 12 September 2026. Portfolio and AI rules have NOT been entered from the official manual. Risky actions remain UNKNOWN / REQUIRE_REVIEW until an authorized policy update.": "Официальные правила портфолио и ИИ сезона 2026–27 ещё не внесены. Ограниченные действия недоступны до проверки и обновления профиля.",
  "Regeneron ISEF 2027 (future-ready)": "Regeneron ISEF 2027",
  "AI may be used as a cited resource, but generative AI must not write protected outputs (research plan, abstract, poster, citations). ISEF approval/safety workflows are NOT automatically satisfied by this app.": "ИИ может использоваться как указанный источник, но не для написания защищённых материалов. Приложение не заменяет процедуры допуска и безопасности ISEF.",
  "VEX / RECF Student-Centered (strict)": "VEX / RECF — строгий режим",
  "RECF Student-Centered Policy treats AI/LLM use to generate, organize, enhance or alter engineering notebook content as non-student-centered. Generative notebook manipulation is blocked. Not an official certification.": "Строгий профиль блокирует генерацию, организацию и изменение содержимого инженерного дневника средствами ИИ. Это не официальная сертификация.",
  "Teams": "Команды",
  "Seasons archived": "Сезоны в архиве",
  "Storage": "Хранилище",
  "across organization teams": "во всех командах организации",
  "Another team can be created from Onboarding.": "Новую команду можно создать в настройке проекта.",
  "Build. Test. Decide. Remember.": "Собирай. Проверяй. Решай. Сохраняй опыт.",
  "· Student engineering evidence platform. Commercial naming clearance remains pending.": "· Платформа инженерных проектов. Проверка коммерческого использования названия ещё не завершена.",
  "GitHub, Onshape, Telegram, Discord, FIRST®, FTC®, VEX®, RECF and ISEF are trademarks of their respective owners. Their use here describes integrations and competition programs only and does not imply endorsement, affiliation or certification.": "Названия сервисов и конкурсов принадлежат их владельцам. Они обозначают совместимость и программы, но не означают партнёрство или сертификацию.",
  "Getting started": "Начало работы",
  "The evidence model": "Структура проекта",
  "Why? and memory": "Обоснования и история",
  "Competition safety": "Правила конкурса",
  "Roles": "Роли",
  "Product help for teams. Engineering docs (architecture, data model, security, policy engine, integrations) live in the repository under": "Справка для команды. Техническая документация находится в репозитории в папке",
  ". Team evidence is private to members.": ". Материалы доступны только участникам команды.",
  "Create a private team (independent or under a school/club organization).": "Создай закрытую команду — отдельно или в составе школы или клуба.",
  "Pick a competition profile. Student-Owned Mode is on by default.": "Выбери профиль конкурса. Защита авторства включена по умолчанию.",
  "Record your first photo or decision from Capture — it works offline.": "Добавь первую фотографию или решение. Записи можно сохранять без интернета.",
  "Connect GitHub under Integrations; commits arrive in the Evidence Inbox automatically.": "Подключи GitHub в разделе подключений. Коммиты будут поступать в материалы проекта.",
  "Source events are append-only records from GitHub, Onshape, chat, CSV or capture.": "Исходные материалы поступают из подключений, CSV и ручных записей. Их исходное содержимое сохраняется.",
  "Iterations group evidence around a meaningful change; tests and decisions attach to them.": "Этап объединяет материалы одного изменения. К нему привязываются испытания и решения.",
  "Typed relations (SUPPORTS, TESTS, SUPERSEDES, …) form the Evidence Trace. Machine suggestions are dashed until you accept them.": "Граф показывает типы связей между записями. Автоматические предложения требуют подтверждения.",
  "Student annotations are versioned; revising never destroys the original.": "Пояснения сохраняют историю изменений. Новая версия не удаляет исходную.",
  "Open any test, decision, iteration or event and press Why? to get a deterministic answer assembled from linked evidence.": "Открой запись и её обоснование, чтобы просмотреть связанные материалы.",
  "Ask Project History searches across seasons and cites stored objects; it says “not documented” instead of guessing.": "Поиск истории охватывает сезоны и ссылается на сохранённые записи. Недостающие данные не додумываются.",
  "The Failure Library keeps rejected approaches findable for future teams.": "Библиотека неудачных подходов сохраняет опыт для следующих участников.",
  "Rules are versioned policy data evaluated on the server for every sensitive action.": "Версии правил проверяются на сервере для каждого ограниченного действия.",
  "VEX strict blocks generative notebook manipulation. FTC 2026–27 remains under review until the official manual is entered. ISEF blocks protected outputs.": "Строгий VEX-профиль блокирует генерацию дневника. Правила FTC 2026–27 требуют проверки. Профиль ISEF защищает конкурсные материалы.",
  "Exports are pinned to the policy version in force and record student vs. generated content IDs.": "Экспорт сохраняет действовавшую версию правил и происхождение включённых материалов.",
  "Students create and own evidence, tests, decisions and reasoning.": "Участники создают материалы, испытания, решения и пояснения.",
  "Student leads organize, invite and export.": "Руководители команды организуют работу, приглашают участников и экспортируют данные.",
  "Coaches see structural gaps and leave coach notes; they cannot edit student content.": "Наставники видят пропущенные связи и оставляют свои заметки, но не редактируют авторский текст.",
  "Organization admins manage teams, retention, billing and audit.": "Администраторы организации управляют командами, хранением и аудитом.",
  "Private by default": "Закрыто по умолчанию",
  "Student ownership": "Авторство участника",
  "AI provenance": "Происхождение текста ИИ",
  "Competition policy gating": "Проверка правил конкурса",
  "Data export & deletion": "Экспорт и удаление данных",
  "No public productivity ranking": "Без рейтинга участников",
  "Integration permissions": "Права подключений",
  "Photo privacy": "Приватность фотографий",
  "Security model": "Защита данных",
  "Youth privacy": "Приватность участников",
  "Every team's evidence is visible only to verified active members of that team. Nothing is public unless an authorized person deliberately exports it.": "Материалы команды доступны её активным участникам. Публикация не происходит автоматически.",
  "Student-authored reasoning is stored with explicit provenance and version history. Coaches and administrators cannot edit or overwrite it — the server refuses, not just the UI.": "Пояснения сохраняются с авторством и историей версий. Сервер запрещает наставникам и администраторам переписывать их.",
  "Source evidence, student annotations, deterministic system data, machine suggestions and AI-generated text are stored as distinct, labeled objects. AI output is logged with policy version, model and hash, and never silently replaces student text.": "Исходные материалы, авторские заметки и текст ИИ хранятся раздельно. Для ИИ фиксируются модель, версия правил и контрольная сумма. Авторский текст не заменяется автоматически.",
  "Competition rules are versioned data evaluated server-side for every sensitive action. Strict profiles block generative notebook manipulation. Seasons whose rules have not been reviewed fail safe: risky actions remain disabled. We do not claim official certification by any competition organizer.": "Правила проверяются на сервере. Строгие профили запрещают генеративное изменение дневника. До проверки правил ограниченные действия недоступны. Официальная сертификация организаторов конкурсов не заявляется.",
  "Students can export their own contribution evidence. Team leads can export team data. Organization admins can export or delete an organization with confirmation and an audit trail. These controls are never paywalled.": "Участник может скачать свой вклад, руководитель — данные команды. Администратор управляет экспортом и удалением организации с подтверждением и аудитом. Эти функции не зависят от тарифа.",
  "We never rank students by commits, entries, uploads, time or 'XP'. Contribution maps are private, evidence-backed and never comparative.": "Участники не ранжируются по коммитам, загрузкам или времени работы. Сведения о вкладе закрыты и не используются для сравнения.",
  "GitHub ingests commit metadata only (SHA, author, message, changed-file counts) — not repository contents. CAD connectors record that a design changed, not why. Connector secrets are encrypted at rest and webhooks are signature-verified.": "GitHub передаёт метаданные коммитов, а не содержимое репозитория. CAD фиксирует изменения, но не их причины. Секреты подключений шифруются; подписи вебхуков проверяются.",
  "Uploaded JPEGs have EXIF/GPS and device metadata stripped. Media is served only through membership-checked, non-guessable, private URLs.": "Из загружаемых JPEG удаляются EXIF, геоданные и сведения об устройстве. Доступ к файлам проверяется по членству в команде.",
  "Scrypt password hashing, httpOnly session cookies, server-side authorization on every team-scoped request, idempotent webhooks, content-type sniffing and size limits on uploads, structured audit events for sensitive actions. See SECURITY.md in the repository for the threat model.": "Используются хеширование паролей, защищённые cookie сессии, серверная проверка доступа, проверка файлов и журнал действий. Модель угроз описана в SECURITY.md.",
  "We collect minimal personal data (email, display name, optional age category). No behavioral advertising, no precise location, no hidden tracking, no public minor profiles. Legal compliance for a given jurisdiction requires review by your organization; we provide the controls.": "Хранятся почта, отображаемое имя и необязательная возрастная категория. Нет поведенческой рекламы и публичных профилей несовершеннолетних. Применимые правовые требования должна проверить организация.",
  "Free Team": "Бесплатная команда",
  "Club": "Клуб",
  "School / Academy": "Школа / Академия",
  "from $19/mo": "от $19 в месяц",
  "contact": "Связаться",
};
